SELECT 
  CAST(LPEP_PICKUP_DATETIME AS DATE) as date_pickup, 
  CAST(LPEP_DROPOFF_DATETIME AS DATE) as date_dropoff, 
  COUNT(1) 
FROM 
  GREEN_TAXI_DATA 
WHERE 
  CAST(LPEP_PICKUP_DATETIME AS DATE) = '2019-01-15' 
  AND CAST(LPEP_DROPOFF_DATETIME AS DATE) = '2019-01-15' 
GROUP BY 
  CAST(LPEP_PICKUP_DATETIME AS DATE), 
  CAST(LPEP_DROPOFF_DATETIME AS DATE);
