SELECT 
  CAST(LPEP_PICKUP_DATETIME AS DATE) as "day", 
  passenger_count, 
  COUNT(1) AS COUNT_TRIPS 
FROM 
  GREEN_TAXI_DATA 
WHERE 
  CAST(LPEP_PICKUP_DATETIME AS DATE) = '2019-01-01' 
  AND PASSENGER_COUNT = 2 
GROUP BY 
  CAST(LPEP_PICKUP_DATETIME AS DATE), 
  passenger_count 
UNION 
SELECT 
  CAST(LPEP_PICKUP_DATETIME AS DATE) as "day", 
  passenger_count, 
  COUNT(1) AS COUNT_TRIPS 
FROM 
  GREEN_TAXI_DATA 
WHERE 
  CAST(LPEP_PICKUP_DATETIME AS DATE) = '2019-01-01' 
  AND PASSENGER_COUNT = 3 
GROUP BY 
  CAST(LPEP_PICKUP_DATETIME AS DATE), 
  passenger_count;
